name: Build LaTeX document
on:
  push:
jobs:
  build_latex:
    container: 
        images: texlive/texlive:latest 
            steps:
                -name: Set up Git repository
                uses: actions/checkout@latest
                -name: compile latex
                run:
                    chmod +x "${GITHUB_WORKSPACE}/.github/compile.sh"
                    "${GITHUB_WORKSPACE}/.github/compile.sh"
                -name: upload 
                uses: actions/upload-artifact@v2
                with:
                    name: thesis.pdf
