name: Build LaTeX document
on:
  push:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: 
      image: texlive/texlive:latest 
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Get previous tag name
        id: previous_tag
        run: |
          which python3
          ls -aR
          python3 .github/git_tag.py
          output=$(python3 .github/git_tag.py)
          echo "::set-output name=TAGNAME::$output"
      - run: "echo tags: ${{ steps.previous_tag.outputs.TAGNAME }}"
#      - name: compile
#        run: |
#          sh  ${GITHUB_WORKSPACE}/.github/compile.sh
#      - name: upload compiled document
#        uses: actions/upload-artifact@v2
#        with:
#          name: thesis.pdf
#          path: thesis.pd
