name: Build LaTeX document
on:
  push:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: 
      image: texlive/texlive:latest 
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Get previous tag name
        id: previous_tag
        env:
          ref: ${{ github.ref }}
        run: |
          output=$(python3 .github/git_tag.py ${ref}) 
          echo "::set-output name=TAGNAME::$output"
      - name: compile
        env:
          tag: ${{ steps.previous_tag.outputs.TAGNAME }}
        run: |
          sh  ${GITHUB_WORKSPACE}/.github/compile.sh ${tag}
      - name: upload compiled document
        uses: actions/upload-artifact@v2
        with:
          name: thesis
          path: |
            build/*.pdf
            diff/*.pdf
