name: Build LaTeX document
on:
  push:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: 
      image: texlive/texlive:latest 
    steps:
      - name: Set up Git repository
        uses: actions/checkout@latest
      - name: compile
        run:
          chmod +x "${GITHUB_WORKSPACE}/.github/compile.sh"
          "${GITHUB_WORKSPACE}/.github/compile.sh"
      - name: upload compiled document
        uses: actions/upload-artifact@latest
        with:
          name: thesis.pdf
